### ISSUE TITLE
Describe how to use CDDL with JSON

### ISSUE THREAD

**Issue by cabo** [cbor-wg/cddl#1]
Today, the spec is written for CBOR, and just implies that CDDL can also be used with JSON.
Since that is [happening](https://tools.ietf.org/html/rfc8007#appendix-A), add an appendix that makes the information explicit which parts of CDDL remain unused with JSON.

Initial attempt of a list:

* CBOR tags
* byte-string constants (h'beef' etc.)
* prelude elements that based on major types #2 and #6 (bstr/bytes, all the tags from tdate to cbor-any)

When mapping the JSON data model (which is not distinguishing integer from floating-point numbers) to that of CBOR, numbers with a zero fractional part become integers.  Details of this may also need some additional information.  Probably also point to I-JSON (RFC7493).

**Comment by linuxwolf** [comment]
This looks like a reasonable start on requirements.

**Comment by cabo** [comment]
Was already addressed in 7ec05db3 and later revisions to that; discussed in Singapore; no recent issues came up with that.  Closing for now (could be re-opened on additional WG input).
