### ISSUE TITLE
Incorrect definition of "entry"

### ISSUE THREAD

**Issue by jyasskin** [cbor-wg/cddl#12]
https://tools.ietf.org/html/draft-ietf-cbor-cddl-02#section-2.1.2 says

> An entry consists of a _keytype_ and a _valuetype_

But the grammar says

>  grpent = [occur S] [memberkey S] type optcom
>        / [occur S] groupname [genericarg] optcom ; preempted by above
>        / [occur S] "(" S group S ")" optcom

which allows entries that aren't just a key and a value.

**Comment by cabo** [comment]
Right, the production name was not changed when grpent gained expressiveness.  Appendix C calls them "group expressions", which maybe isn't that great either because there is also "group".
What would be a good name for the things that are optionally separated by commas in a group expression?

**Comment by cabo** [comment]
Closed in b0399e8
