### ISSUE TITLE
Which data model do .eq and .ne use?

### ISSUE THREAD

**Issue by jyasskin** [cbor-wg/cddl#18]
Now that CBOR allows protocols to specify that CBOR values that are distinct in the [basic generic data model](https://cbor-wg.github.io/CBORbis/#cbor-data-models) are equivalent in the protocol's [specific data model](https://cbor-wg.github.io/CBORbis/#rfc.section.2.2), CDDL should specify which of those data models `.eq` and`.ne` use, or explicitly allow CBOR-based protocols to decide.

**Comment by cabo** [comment]
A CDDL tool can't know the specific data model.  So I would assume that we use the basic generic data model.  The text hints that the inequalities are about numeric values, so

```
number .ge 1
```

would match both 2 and 2.5.

This is indeed less clear for .eq/.ne, and maybe we need .eql/.equal as well.  But right now the text is mute about that, so we don't know whether

```
number .ne 0
```

includes 0.0 (or –0.0!) or not.

This probably needs a bit more discussion, but it should not be too hard to come up with a workable solution.  We probably should simply copy some existing language definition here — to be found.
