### ISSUE TITLE
Mailing list link is broken in CONTRIBUTING.md

### ISSUE THREAD

**Issue by oliviermartin** [cbor-wg/cddl#27]
See: https://github.com/cbor-wg/cddl/blob/master/CONTRIBUTING.md#other-resources

Is `cbor` mailing-list used instead? I have just seen some CDDL related messages on it: https://mailarchive.ietf.org/arch/browse/cbor/

**Comment by cabo** [comment]
Thank you -- apparently, this was autogenerated based on some heuristic that didn't quite work.
